export const currentClasses = state => state.currentClasses
export const currentCourses = state => state.currentCourses
export const currentCourse = state => state.currentCourse
export const oldCourses = state => state.oldCourses
export const oldCourse = state => state.oldCourse
export const remoteData = state => state.remoteData
export const eWordsArr = state => state.eWordsArr
export const cWordsArr = state => state.cWordsArr
export const nonsArr = state => state.nonsArr
export const needUnlock = state => state.needUnlock
export const needLightStar = state => state.needLightStar